version: '3.7'

services:
  client:
    restart: always
    container_name: client
    build: client/
    command: python client.py server 1200
    networks:
    - app-net
    ports:
      - "1234:1234/udp"

  server:
    restart: always
    container_name: server
    build: server/
    command: python server.py client 1234
    networks:
    - app-net
    ports:
    - "1200:1200/udp"

networks:
  app-net:
    driver: bridge
